AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: velinfo.fr serveless application

Globals:
  Function:
    Timeout: 50

Parameters:
  CDNCertificateArn:
    Type: String
  APICertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  FrontendBucketName:
    Type: String

Resources:
  # Lambdas
  FetchStationsAvailabilities:
    Type: AWS::Serverless::Function
    DependsOn: CurrentAvailabilityTable
    Properties:
      FunctionName: FetchStationsAvailabilities
      Description: Fetch the station availabilities from the Paris API every minute and update the current availability dynamo table
      CodeUri: lambda/FetchStationsAvailabilities
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          AVAILABILITY_TABLE_NAME: !Ref CurrentAvailabilityTable
      Events:
          EveryMinute:
            Type: Schedule
            Properties:
              Schedule: rate(1 minute)
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref CurrentAvailabilityTable

  FetchStationsCharacteristics:
    Type: AWS::Serverless::Function
    DependsOn: CurrentCharacteristicsTable
    Properties:
      FunctionName: FetchStationsCharacteristics
      Description: Fetch the station characteristics from the Velib API every hour and update the current characteristics dynamo table
      CodeUri: lambda/FetchStationsCharacteristics
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          CHARACTERISTICS_TABLE_NAME: !Ref CurrentCharacteristicsTable
      Events:
          EveryHour:
            Type: Schedule
            Properties:
              Schedule: rate(1 hour)
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref CurrentCharacteristicsTable

  ComputeHourlyStatistics:
    Type: AWS::Serverless::Function
    DependsOn:
      - CurrentAvailabilityTable
      - HourlyStatisticsTable
    Properties:
      FunctionName: ComputeHourlyStatistics
      Description: Process every update of the current availability table to compute hourly usage stats for each station
      CodeUri: lambda/ComputeHourlyStatistics
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          STATION_HOURLY_STATISTICS_TABLE_NAME: !Ref HourlyStatisticsTable
      Events:
        StreamAvailability:
          Type: DynamoDB
          Properties:
            Stream: 
              !GetAtt CurrentAvailabilityTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 1
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref HourlyStatisticsTable

  ComputeGlobalDailyStatistics:
    Type: AWS::Serverless::Function
    DependsOn:
      - CurrentAvailabilityTable
      - GlobalDailyStatisticsTable
    Properties:
      FunctionName: ComputeGlobalDailyStatistics
      Description: Process every update of the current availability table to compute global daily usage stats
      CodeUri: lambda/ComputeGlobalDailyStatistics
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          GLOBAL_DAILY_STATISTICS_TABLE_NAME: !Ref GlobalDailyStatisticsTable
      Events:
        StreamAvailability:
          Type: DynamoDB
          Properties:
            Stream: 
              !GetAtt CurrentAvailabilityTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 1
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref GlobalDailyStatisticsTable

  ComputeExpectedActivities:
    Type: AWS::Serverless::Function
    DependsOn: 
      - HourlyStatisticsTable
      - ExpectedActivityTable
    Properties:
      FunctionName: ComputeExpectedActivities
      Description: Compute the expected station activity per week day and hour
      CodeUri: lambda/ComputeExpectedActivities
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          STATION_HOURLY_STATISTICS_TABLE_NAME: !Ref HourlyStatisticsTable
          EXPECTED_ACTIVITY_TABLE_NAME: !Ref ExpectedActivityTable
      Events:
          EveryHour:
            Type: Schedule
            Properties:
              Schedule: rate(1 hour)
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref HourlyStatisticsTable
      - DynamoDBCrudPolicy:
          TableName: !Ref ExpectedActivityTable

  ComputeStationsStates:
    Type: AWS::Serverless::Function
    DependsOn:
      - StationStateTable
      - CurrentAvailabilityTable
    Properties:
      FunctionName: ComputeStationsStates
      Description: Compute the state of each station
      CodeUri: lambda/ComputeStationsStates
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment: 
        Variables:
          STATES_TABLE_NAME: !Ref StationStateTable
          EXPECTED_ACTIVITY_TABLE_NAME: !Ref ExpectedActivityTable
          COLD_THRESHOLD_MINUTES_MIN: 5
          COLD_THRESHOLD_MINUTES_MAX: 2160 #36 hours
          LOCKED_ACTIVITY_THRESHOLD: 50
      Events:
        StreamAvailability:
          Type: DynamoDB
          Properties:
            Stream: 
              !GetAtt CurrentAvailabilityTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 1
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref StationStateTable
      - DynamoDBCrudPolicy:
          TableName: !Ref ExpectedActivityTable
  
  GetStations:
    Type: AWS::Serverless::Function
    DependsOn:
      - GlobalDailyStatisticsTable
      - CurrentAvailabilityTable
      - CurrentCharacteristicsTable
    Properties:
      FunctionName: GetStations
      Description: Get the current stations states
      CodeUri: lambda/GetStations
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 1769 #minimal memory to have a full vCPU
      Environment: 
        Variables:
          STATES_TABLE_NAME: !Ref StationStateTable
          AVAILABILITY_TABLE_NAME: !Ref CurrentAvailabilityTable
          CHARACTERISTICS_TABLE_NAME: !Ref CurrentCharacteristicsTable
      Tracing: Active
      Events:
        GetApi:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /stations
            Method: GET
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref StationStateTable
      - DynamoDBCrudPolicy:
          TableName: !Ref CurrentAvailabilityTable
      - DynamoDBCrudPolicy:
          TableName: !Ref CurrentCharacteristicsTable

  GetGlobalStatistics:
    Type: AWS::Serverless::Function
    DependsOn:
      - GlobalDailyStatisticsTable
    Properties:
      FunctionName: GetGlobalStatistics
      Description: Get todays global statistics
      CodeUri: lambda/GetGlobalStatistics
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 1769 #minimal memory to have a full vCPU
      Environment: 
        Variables:
          GLOBAL_DAILY_STATISTICS_TABLE_NAME: !Ref GlobalDailyStatisticsTable
      Tracing: Active
      Events:
        GetApi:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /global-statistics
            Method: GET
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref GlobalDailyStatisticsTable

  GetExpectedActivities:
    Type: AWS::Serverless::Function
    DependsOn:
      - ExpectedActivityTable
    Properties:
      FunctionName: GetExpectedActivities
      Description: Get todays expected activities for each stations
      CodeUri: lambda/GetExpectedActivities
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 1769 #minimal memory to have a full vCPU
      Environment: 
        Variables:
          EXPECTED_ACTIVITY_TABLE_NAME: !Ref ExpectedActivityTable
      Tracing: Active
      Events:
        GetApi:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /expected-activities
            Method: GET
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref GlobalDailyStatisticsTable
     
  # Dynamo tables
  CurrentAvailabilityTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: CurrentAvailability
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S 
      ProvisionedThroughput: 
        ReadCapacityUnits: 3
        WriteCapacityUnits: 4
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  CurrentCharacteristicsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: CurrentCharacteristics
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S 
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 3

  HourlyStatisticsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: HourlyStatistics
      KeySchema: 
        - AttributeName: stats_day
          KeyType: HASH
        - AttributeName: stats_datetime
          KeyType: RANGE
      AttributeDefinitions:
      - AttributeName: stats_day
        AttributeType: S
      - AttributeName: stats_datetime
        AttributeType: S
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TimeToLiveSpecification:
        AttributeName : timetolive
        Enabled : true

  GlobalDailyStatisticsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: GlobalDailyStatistics
      KeySchema: 
        - AttributeName: stats_day
          KeyType: HASH
      AttributeDefinitions:
      - AttributeName: stats_day
        AttributeType: S
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName : timetolive
        Enabled : true
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ExpectedActivityTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: ExpectedActivity
      KeySchema: 
        - AttributeName: weekday
          KeyType: HASH
        - AttributeName: hour
          KeyType: RANGE
      AttributeDefinitions:
      - AttributeName: weekday
        AttributeType: N
      - AttributeName: hour
        AttributeType: N
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 1

  StationStateTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: StationState
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S 
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  #Rest API
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Velinfo REST Api
      StageName: Production
      Domain:
        DomainName: api.velinfo.fr
        CertificateArn: 
          Ref: APICertificateArn
        Route53:
          HostedZoneId: 
            Ref: HostedZoneId

  #Website
  WebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Ref: FrontendBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  CDNOriginIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: "Cloudfront Origin identity for www.velinfo.Fr"

  CDN:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - 'www.velinfo.fr'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: 'true'
          ForwardedValues:
            QueryString: True
          TargetOriginId: !Sub "S3-origin-${WebsiteS3Bucket}"
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        CustomErrorResponses:
        - ErrorCachingMinTTL: 10
          ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCachingMinTTL: 10
          ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        Enabled: True
        Origins:
          - DomainName: !GetAtt WebsiteS3Bucket.RegionalDomainName
            Id: !Sub "S3-origin-${WebsiteS3Bucket}"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CDNOriginIdentity}"
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CDNCertificateArn
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only

  WebsiteS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteS3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CDNOriginIdentity}"
            Resource: !Sub "arn:aws:s3:::${WebsiteS3Bucket}/*"
        Version: "2012-10-17"

  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub 'www.velinfo.fr'
          Type: A
          AliasTarget:
            DNSName: !GetAtt CDN.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  WebsiteBucketUrl:
    Description: 'S3 Bucket Url'
    Value: !GetAtt 'WebsiteS3Bucket.WebsiteURL'
    